import { step, workflow } from 'gagen';

const checkout = step({
  uses: 'actions/checkout@v6',
  with: {
    'fetch-depth': 0,
    filter: 'tree:0',
  },
});

const installPnpm = step({
  name: 'Install pnpm',
  uses: 'pnpm/action-setup@v5.0.0',
  with: {
    run_install: false,
  },
});

const setupNode = step({
  uses: 'actions/setup-node@v6',
  with: {
    cache: 'pnpm',
    'node-version': 24,
  },
});

const install = step({
  run: 'pnpm install --frozen-lockfile',
});

const dedupe = step({
  name: '👯 Check for Duplicate Dependencies',
  run: 'pnpm dedupe --check',
});

const nxSetShas = step({
  uses: 'nrwl/nx-set-shas@v5.0.1',
});

const knip = step({
  name: '✂️ Knip',
  run: 'pnpm exec knip --reporter github-actions',
});

const checkFormat = step({
  name: '🎨 Check Format',
  run: 'pnpm exec nx format:check',
});

const nxAffected = step({
  run: 'pnpm exec nx affected -t lint test build typecheck',
});

const lintWorkflows = step({
  name: 'Lint Workflow Generation',
  run: 'pnpm run workflows:lint',
});

workflow({
  jobs: [
    {
      id: 'main',
      name: 'CI',
      runsOn: 'ubuntu-latest',
      steps: [
        checkout,
        installPnpm,
        setupNode,
        install,
        dedupe,
        nxSetShas,
        knip,
        checkFormat,
        nxAffected,
        lintWorkflows,
      ],
    },
  ],
  name: 'CI',
  on: {
    pull_request: {},
    push: { branches: ['main'] },
  },
  permissions: {
    actions: 'read',
    contents: 'read',
  },
}).writeOrLint({
  filePath: new URL('./ci.generated.yml', import.meta.url),
  header: '# GENERATED BY .github/workflows/ci.ts -- DO NOT DIRECTLY EDIT',
});
