import { step, workflow } from '@david/gagen';

const checkout = step({
  uses: 'actions/checkout@v6',
  with: {
    'fetch-depth': 0,
  },
});

const installPnpm = step({
  name: 'Install pnpm',
  uses: 'pnpm/action-setup@v5.0.0',
  with: {
    run_install: false,
  },
});

const setupNode = step({
  uses: 'actions/setup-node@v6',
  with: {
    cache: 'pnpm',
    'node-version': 24,
    'registry-url': 'https://registry.npmjs.org',
  },
});

const useNpmForOidc = step({
  name: 'Use npm for OIDC',
  run: 'npm install -g npm@11.5.2',
});

const install = step({
  name: 'Install dependencies',
  run: 'pnpm install --frozen-lockfile',
});

const build = step({
  name: 'Build packages',
  run: 'pnpm exec nx run-many -t build',
});

const extractProjectName = step({
  id: 'project',
  name: 'Extract project name from release tag',
  run: `# Extract project name from tag (e.g., "npm2jsr@0.2.0" -> "npm2jsr")
TAG="\${{ github.event.release.tag_name }}"
PROJECT="\${TAG%@*}"
echo "name=\${PROJECT}" >> $GITHUB_OUTPUT`,
});

const dryRunNpm = step({
  env: {
    NPM_CONFIG_PROVENANCE: true,
  },
  name: 'Dry run npm publish',
  run: 'pnpm exec nx release publish --projects=${{ steps.project.outputs.name }} --dry-run',
});

const dryRunJsr = step({
  name: 'Dry run JSR publish',
  run: 'pnpm jsr publish --dry-run',
  workingDirectory: './packages/${{ steps.project.outputs.name }}',
});

const publishNpm = step({
  env: {
    NPM_CONFIG_PROVENANCE: true,
  },
  name: 'Publish to npm',
  run: 'pnpm exec nx release publish --projects=${{ steps.project.outputs.name }}',
});

const publishJsr = step({
  name: 'Publish to JSR',
  run: 'pnpm jsr publish',
  workingDirectory: './packages/${{ steps.project.outputs.name }}',
});

workflow({
  jobs: [
    {
      id: 'publish',
      runsOn: 'ubuntu-latest',
      steps: [
        checkout,
        installPnpm,
        setupNode,
        useNpmForOidc,
        install,
        build,
        extractProjectName,
        dryRunNpm,
        dryRunJsr,
        publishNpm,
        publishJsr,
      ],
    },
  ],
  name: 'Publish',
  on: {
    release: { types: ['published'] },
  },
  permissions: {
    contents: 'read',
    'id-token': 'write',
  },
}).writeOrLint({
  filePath: new URL('./publish.generated.yml', import.meta.url),
  header: '# GENERATED BY .github/workflows/publish.ts -- DO NOT DIRECTLY EDIT',
});
