name: Publish to JSR

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write # for JSR provenance

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm exec nx run-many -t build

      - name: Extract project name from release tag
        id: project
        run: |
          # Extract project name from tag (e.g., "npm2jsr@0.2.0" -> "npm2jsr")
          TAG="${{ github.event.release.tag_name }}"
          PROJECT="${TAG%@*}"
          echo "name=${PROJECT}" >> $GITHUB_OUTPUT

      - name: Dry run npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          chmod 600 ~/.npmrc
          pnpm exec nx release publish --projects=${{ steps.project.outputs.name }} --dry-run

      - name: Publish to JSR
        run: npx jsr publish
        working-directory: ./packages/${{ steps.project.outputs.name }}
