import { step, workflow } from '@david/gagen';

const checkout = step({
  uses: 'actions/checkout@v6',
  with: {
    'fetch-depth': 0,
    token: '${{ secrets.RELEASE_PAT_TOKEN }}',
  },
});

const installPnpm = step({
  name: 'Install pnpm',
  uses: 'pnpm/action-setup@v5.0.0',
  with: {
    run_install: false,
  },
});

const setupNode = step({
  uses: 'actions/setup-node@v6',
  with: {
    cache: 'pnpm',
    'node-version': 24,
  },
});

const install = step({
  name: 'Install dependencies',
  run: 'pnpm install --frozen-lockfile',
});

const build = step({
  name: 'Build packages',
  run: 'pnpm exec nx run-many -t build',
});

const configureGit = step({
  name: 'Configure Git',
  run: `git config user.name "cylewaitforit"
git config user.email "cyle@cylewaitfor.it"
git remote set-url origin https://x-access-token:\${{ secrets.RELEASE_PAT_TOKEN }}@github.com/\${{ github.repository }}.git`,
});

const versionPackages = step({
  env: {
    GH_TOKEN: '${{ secrets.RELEASE_PAT_TOKEN }}',
  },
  name: 'Version packages and create releases',
  run: 'node --experimental-strip-types tools/scripts/version.ts',
});

workflow({
  jobs: [
    {
      id: 'release',
      runsOn: 'ubuntu-latest',
      steps: [
        checkout,
        installPnpm,
        setupNode,
        install,
        build,
        configureGit,
        versionPackages,
      ],
    },
  ],
  name: 'Release',
  on: {
    push: { branches: ['main'] },
  },
  permissions: {
    contents: 'write',
    'pull-requests': 'write',
  },
}).writeOrLint({
  filePath: new URL('./release.generated.yml', import.meta.url),
  header: '# GENERATED BY .github/workflows/release.ts -- DO NOT DIRECTLY EDIT',
});
